### ISSUE TITLE
Build.py failed

### ISSUE THREAD

**Issue by cohearne77** [gsheppar/Prisma-SD-WAN-Deploy-Make#2]
I have been unable to get this work for the most part, 

issue 1 is with the version of SDK (CloudGenix SDK v5.6.1b2) recommended in the readme, the gui is unable to pull a list of sites,

I updated the SDK to the latest version (6.1.1b1) and the pull works along with with the csv and jinja templates.

issue 2,  I'm unable to use the build.py 
(Starting push of ./Configs/test.yaml . Please wait...
Deployment failed for ./Configs/test.yaml) 

using python 3.7 and tried with 3.10 

all requirements installed ok except numpy which need 3.8 for 1.22.0 however running 1.20.1

Thanks

**Comment by gsheppar** [comment]
Thanks
Updated Read Me - It should be 6.1.1b1
Updated the Make and Build - Try make a new jinja file and then push via the build again

**Comment by cohearne77** [comment]
Legend, the build.py is working now and was able to deploy a new site. don't understand the cloudgenix_config version, I can't seem to find anything higher than 1.7 but again doesn't seem to be affecting anything.

Thanks for updating
